trigger:
- main

stages:

- stage: Build
  jobs:
  - job: BuildPackage
    steps:
    - script: echo Building UiPath package

- stage: DeployDev
  dependsOn: Build
  jobs:
  - job: DeployToDev
    steps:
    - script: echo Deploying to Dev

- stage: DeployProd
  dependsOn: DeployDev
  jobs:
  - job: DeployToProd
    steps:
    - script: echo Deploying to Prod